name: Test
permissions:
  contents: read

on:
  push:
    branches:
      - '**'

jobs:

  test:
    strategy:
      matrix:
        go: [1.25.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
        GOFLAGS: -mod=readonly

    steps:
    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

    - name: Test
      run: go test -race -parallel 1 -short ./internal/...

    - name: Build
      run: go build -race ./cmd/server/main.go